image:
- Visual Studio 2017

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  matrix:
    # MSVC
    - TARGET: x86_64-pc-windows-msvc

install:
  - ps: |
      If ($Env:TARGET -eq 'x86_64-pc-windows-gnu') {
        $Env:PATH += ';C:\msys64\mingw64\bin'
      } ElseIf ($Env:TARGET -eq 'i686-pc-windows-gnu') {
        $Env:PATH += ';C:\msys64\mingw32\bin'
      }
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      cd C:\tools\vcpkg
      git checkout d82f37b4bfc1422d4601fbb63cbd553c925f7014
      vcpkg integrate install
      vcpkg install boost-filesystem:x64-windows boost-program-options:x64-windows boost-thread:x64-windows boost-python:x64-windows eigen3:x64-windows
      cd C:\tools
      Invoke-WebRequest -uri https://www.python.org/ftp/python/3.6.4/python-3.6.4-embed-amd64.zip -OutFile python-3.6.4-embed-amd64.zip
      [System.IO.Compression.ZipFile]::ExtractToDirectory("../python-3.6.4-embed-amd64.zip", "Python364")
      cd $env:APPVEYOR_BUILD_FOLDER
      git clone https://github.com/YosysHQ/nextpnr.git
      cd nextpnr
      git checkout 3f26cf50767143e48d29ae691b2a0052c359eb15
      [System.IO.Compression.ZipFile]::ExtractToDirectory("C:/tools/Python364/python36.zip", "Lib")
      cmake -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DARCH=ice40 -DICEBOX_ROOT=../icebox -DCMAKE_TOOLCHAIN_FILE=C:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -G "Visual Studio 15 2017 Win64" -DPYTHON_EXECUTABLE=C:/tools/Python364/python.exe -DPYTHON_LIBRARY=C:/tools/vcpkg/packages/python3_x64-windows/lib/python36.lib -DPYTHON_INCLUDE_DIR=C:/tools/vcpkg/packages/python3_x64-windows/include/python3.6 -DSTATIC_BUILD=ON -DBUILD_GUI=OFF .
      cmake --build . --config Release
# # TODO This is the "test phase", tweak it as you see fit
# test_script:
#   # we don't run the "test phase" when doing deploys
#   - if [%APPVEYOR_REPO_TAG%]==[false] (
#       cargo build --target %TARGET% &&
#       cargo build --target %TARGET% --release
#     )

# before_deploy:
  # TODO Update this to build the artifacts that matter to you
  # - ps: ci\before_deploy.ps1

deploy:
  artifact: /.*\.zip/
  auth_token:
    secure: '6eJOjWv2eburw+V4lUSkAN5OCs1fYr1C96WgULOZzgYDT7DLhC0oaaGuN9jeIw6z'
  description: 'Automated release'
  on:
    # TODO Here you can pick which targets will generate binary releases
    # In this example, there are some targets that are tested using the stable
    # and nightly channels. This condition makes sure there is only one release
    # for such targets and that's generated using the stable channel
    RUST_VERSION: stable
    appveyor_repo_tag: true
  provider: GitHub

cache:
  - c:\tools\vcpkg\installed\
  - C:\tools\Python364

branches:
  only:
    # Release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  - provider: Email
    to:
      - sean@xobs.io
    on_build_status_changed: true
    on_build_success: false

# Building is done in the test phase, so we disable Appveyor's build phase.
build: false